// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleInspectionAppointmentSystem.Infrastructure.Common;

#nullable disable

namespace VehicleInspectionAppointmentSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630171447_ChangePasswordAccessabilityInTheUserTable")]
    partial class ChangePasswordAccessabilityInTheUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.Appointments.Entity.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TimeSlotId")
                        .IsUnique();

                    b.HasIndex("VehicleId", "TimeSlotId")
                        .IsUnique();

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 450000m,
                            PaymentType = "Card",
                            Status = "Active",
                            TimeSlotId = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 450000m,
                            PaymentType = "credit",
                            Status = "Done",
                            TimeSlotId = 2,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 520000m,
                            PaymentType = "Card",
                            Status = "Active",
                            TimeSlotId = 4,
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 0m,
                            PaymentType = "Card",
                            Status = "Cancelled",
                            TimeSlotId = 6,
                            VehicleId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 600000m,
                            PaymentType = "credit",
                            Status = "Done",
                            TimeSlotId = 8,
                            VehicleId = 5
                        },
                        new
                        {
                            Id = 6,
                            Amount = 450000m,
                            PaymentType = "Card",
                            Status = "Active",
                            TimeSlotId = 10,
                            VehicleId = 6
                        },
                        new
                        {
                            Id = 7,
                            Amount = 300000m,
                            PaymentType = "Card",
                            Status = "Done",
                            TimeSlotId = 12,
                            VehicleId = 7
                        },
                        new
                        {
                            Id = 8,
                            Amount = 650000m,
                            PaymentType = "credit",
                            Status = "Active",
                            TimeSlotId = 14,
                            VehicleId = 8
                        });
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.Centers.Entity.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CenterCode")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DailyMaxCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ManagerName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CenterCode")
                        .IsUnique();

                    b.HasIndex("CityId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Centers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "No. 15, Shariati Street, Tehran",
                            CenterCode = 1001,
                            CityId = 1,
                            DailyMaxCapacity = 20,
                            ManagerName = "Michael Anderson",
                            Name = "North Tehran Technical Inspection Center",
                            PhoneNumber = "09121001001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "No. 42, Azadi Avenue, Tehran",
                            CenterCode = 1002,
                            CityId = 1,
                            DailyMaxCapacity = 18,
                            ManagerName = "Daniel Brown",
                            Name = "West Tehran Vehicle Inspection Center",
                            PhoneNumber = "09121001002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "No. 8, Imam Street, Rey",
                            CenterCode = 1003,
                            CityId = 2,
                            DailyMaxCapacity = 15,
                            ManagerName = "Robert Wilson",
                            Name = "Rey Central Inspection Center",
                            PhoneNumber = "09121001003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "No. 22, Chaharbagh Avenue, Isfahan",
                            CenterCode = 2001,
                            CityId = 3,
                            DailyMaxCapacity = 20,
                            ManagerName = "James Miller",
                            Name = "Isfahan Main Inspection Center",
                            PhoneNumber = "09121002001"
                        },
                        new
                        {
                            Id = 5,
                            Address = "No. 11, Fin Road, Kashan",
                            CenterCode = 2002,
                            CityId = 4,
                            DailyMaxCapacity = 14,
                            ManagerName = "William Davis",
                            Name = "Kashan Vehicle Safety Center",
                            PhoneNumber = "09121002002"
                        },
                        new
                        {
                            Id = 6,
                            Address = "No. 31, Zand Boulevard, Shiraz",
                            CenterCode = 3001,
                            CityId = 5,
                            DailyMaxCapacity = 20,
                            ManagerName = "Thomas Moore",
                            Name = "Shiraz Central Technical Inspection",
                            PhoneNumber = "09121003001"
                        },
                        new
                        {
                            Id = 7,
                            Address = "No. 19, Persepolis Road, Marvdasht",
                            CenterCode = 3002,
                            CityId = 6,
                            DailyMaxCapacity = 12,
                            ManagerName = "Christopher Taylor",
                            Name = "Marvdasht Vehicle Inspection Station",
                            PhoneNumber = "09121003002"
                        },
                        new
                        {
                            Id = 8,
                            Address = "No. 61, Vakilabad Boulevard, Mashhad",
                            CenterCode = 4001,
                            CityId = 7,
                            DailyMaxCapacity = 19,
                            ManagerName = "Matthew Clark",
                            Name = "Mashhad East Inspection Center",
                            PhoneNumber = "09121004001"
                        },
                        new
                        {
                            Id = 9,
                            Address = "No. 5, Attar Street, Neyshabur",
                            CenterCode = 4002,
                            CityId = 8,
                            DailyMaxCapacity = 13,
                            ManagerName = "Anthony Lewis",
                            Name = "Neyshabur Technical Inspection Center",
                            PhoneNumber = "09121004002"
                        },
                        new
                        {
                            Id = 10,
                            Address = "No. 77, Elgoli Road, Tabriz",
                            CenterCode = 5001,
                            CityId = 9,
                            DailyMaxCapacity = 20,
                            ManagerName = "Mark Walker",
                            Name = "Tabriz Main Vehicle Inspection Center",
                            PhoneNumber = "09121005001"
                        },
                        new
                        {
                            Id = 11,
                            Address = "No. 14, Sahand Avenue, Maragheh",
                            CenterCode = 5002,
                            CityId = 10,
                            DailyMaxCapacity = 11,
                            ManagerName = "Steven Hall",
                            Name = "Maragheh Road Safety Inspection Center",
                            PhoneNumber = "09121005002"
                        });
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.CityEntity.Entity.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ProvinceCode")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityCode")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityCode = 101,
                            Name = "Tehran",
                            ProvinceCode = 21,
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            CityCode = 102,
                            Name = "Rey",
                            ProvinceCode = 21,
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 3,
                            CityCode = 201,
                            Name = "Isfahan",
                            ProvinceCode = 31,
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 4,
                            CityCode = 202,
                            Name = "Kashan",
                            ProvinceCode = 31,
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 5,
                            CityCode = 301,
                            Name = "Shiraz",
                            ProvinceCode = 71,
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 6,
                            CityCode = 302,
                            Name = "Marvdasht",
                            ProvinceCode = 71,
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 7,
                            CityCode = 401,
                            Name = "Mashhad",
                            ProvinceCode = 51,
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 8,
                            CityCode = 402,
                            Name = "Neyshabur",
                            ProvinceCode = 51,
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 9,
                            CityCode = 501,
                            Name = "Tabriz",
                            ProvinceCode = 41,
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 10,
                            CityCode = 502,
                            Name = "Maragheh",
                            ProvinceCode = 41,
                            ProvinceId = 5
                        });
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.ProvinceEntity.Entity.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProvinceCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProvinceCode")
                        .IsUnique();

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tehran",
                            ProvinceCode = 101
                        },
                        new
                        {
                            Id = 2,
                            Name = "Isfahan",
                            ProvinceCode = 102
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fars",
                            ProvinceCode = 103
                        },
                        new
                        {
                            Id = 4,
                            Name = "Khorasan Razavi",
                            ProvinceCode = 104
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mazandaran",
                            ProvinceCode = 105
                        });
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.TechnicalInspectionEntity.Entity.TechnicalInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("VehicleVin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("VehicleId");

                    b.ToTable("TechnicalInspections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            Description = "Vehicle passed all technical and emission checks successfully.",
                            ExpireDate = new DateTime(2027, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Result = "Passed",
                            VehicleId = 1,
                            VehiclePlate = "12A34567",
                            VehicleVin = "JTDBR32E530123456"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            Description = "Inspection completed successfully with no critical issues.",
                            ExpireDate = new DateTime(2027, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Result = "Passed",
                            VehicleId = 2,
                            VehiclePlate = "23B45678",
                            VehicleVin = "JHMFA16586S123456"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 3,
                            Description = "Vehicle failed due to brake system performance below standard.",
                            ExpireDate = new DateTime(2027, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Result = "Failed",
                            VehicleId = 3,
                            VehiclePlate = "34C56789",
                            VehicleVin = "5YJ3E1EA7KF123456"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 5,
                            Description = "Inspection rejected because required vehicle documents were incomplete.",
                            ExpireDate = new DateTime(2027, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Result = "Rejected",
                            VehicleId = 5,
                            VehiclePlate = "56E78901",
                            VehicleVin = "WF0XXXTTGXK123456"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 7,
                            Description = "Motorcycle passed safety, lighting and emission inspection.",
                            ExpireDate = new DateTime(2027, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Result = "Passed",
                            VehicleId = 7,
                            VehiclePlate = "78G90123",
                            VehicleVin = "MLHPC4567M5123456"
                        });
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.TimeSlotEntity.Entity.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsReserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("TimeSlotDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 5,
                            CenterId = 1,
                            EndTime = new TimeOnly(8, 30, 0),
                            IsReserved = true,
                            StartTime = new TimeOnly(8, 0, 0),
                            TimeSlotDate = new DateTime(2027, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 5,
                            CenterId = 1,
                            EndTime = new TimeOnly(9, 0, 0),
                            IsReserved = true,
                            StartTime = new TimeOnly(8, 30, 0),
                            TimeSlotDate = new DateTime(2027, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 6,
                            CenterId = 1,
                            EndTime = new TimeOnly(9, 30, 0),
                            IsReserved = false,
                            StartTime = new TimeOnly(9, 0, 0),
                            TimeSlotDate = new DateTime(2027, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4,
                            CenterId = 2,
                            EndTime = new TimeOnly(10, 30, 0),
                            IsReserved = true,
                            StartTime = new TimeOnly(10, 0, 0),
                            TimeSlotDate = new DateTime(2027, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 4,
                            CenterId = 2,
                            EndTime = new TimeOnly(11, 0, 0),
                            IsReserved = false,
                            StartTime = new TimeOnly(10, 30, 0),
                            TimeSlotDate = new DateTime(2027, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 7,
                            CenterId = 3,
                            EndTime = new TimeOnly(11, 30, 0),
                            IsReserved = true,
                            StartTime = new TimeOnly(11, 0, 0),
                            TimeSlotDate = new DateTime(2027, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 6,
                            CenterId = 4,
                            EndTime = new TimeOnly(12, 30, 0),
                            IsReserved = false,
                            StartTime = new TimeOnly(12, 0, 0),
                            TimeSlotDate = new DateTime(2027, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 5,
                            CenterId = 5,
                            EndTime = new TimeOnly(13, 30, 0),
                            IsReserved = true,
                            StartTime = new TimeOnly(13, 0, 0),
                            TimeSlotDate = new DateTime(2027, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 5,
                            CenterId = 6,
                            EndTime = new TimeOnly(14, 0, 0),
                            IsReserved = false,
                            StartTime = new TimeOnly(13, 30, 0),
                            TimeSlotDate = new DateTime(2027, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 8,
                            CenterId = 7,
                            EndTime = new TimeOnly(14, 30, 0),
                            IsReserved = true,
                            StartTime = new TimeOnly(14, 0, 0),
                            TimeSlotDate = new DateTime(2027, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 8,
                            CenterId = 8,
                            EndTime = new TimeOnly(15, 0, 0),
                            IsReserved = false,
                            StartTime = new TimeOnly(14, 30, 0),
                            TimeSlotDate = new DateTime(2027, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 4,
                            CenterId = 9,
                            EndTime = new TimeOnly(15, 30, 0),
                            IsReserved = true,
                            StartTime = new TimeOnly(15, 0, 0),
                            TimeSlotDate = new DateTime(2027, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 4,
                            CenterId = 10,
                            EndTime = new TimeOnly(16, 0, 0),
                            IsReserved = false,
                            StartTime = new TimeOnly(15, 30, 0),
                            TimeSlotDate = new DateTime(2027, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 6,
                            CenterId = 11,
                            EndTime = new TimeOnly(16, 30, 0),
                            IsReserved = true,
                            StartTime = new TimeOnly(16, 0, 0),
                            TimeSlotDate = new DateTime(2027, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 6,
                            CenterId = 1,
                            EndTime = new TimeOnly(17, 0, 0),
                            IsReserved = false,
                            StartTime = new TimeOnly(16, 30, 0),
                            TimeSlotDate = new DateTime(2027, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.UserEntity.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("_password")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1990, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "David",
                            FirstName = "John",
                            LastName = "Smith",
                            NationalCode = "1234567890",
                            PhoneNumber = "09123000001",
                            Role = 0,
                            UserName = "09123000001"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1988, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "Robert",
                            FirstName = "Emily",
                            LastName = "Johnson",
                            NationalCode = "1234567891",
                            PhoneNumber = "09123000002",
                            Role = 0,
                            UserName = "09123000002"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1995, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "James",
                            FirstName = "Michael",
                            LastName = "Williams",
                            NationalCode = "1234567892",
                            PhoneNumber = "09123000003",
                            Role = 0,
                            UserName = "09123000003"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1992, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "Thomas",
                            FirstName = "Sarah",
                            LastName = "Brown",
                            NationalCode = "1234567893",
                            PhoneNumber = "09123000004",
                            Role = 0,
                            UserName = "09123000004"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1985, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "George",
                            FirstName = "David",
                            LastName = "Jones",
                            NationalCode = "1234567894",
                            PhoneNumber = "09123000005",
                            Role = 0,
                            UserName = "09123000005"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1993, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "Edward",
                            FirstName = "Jessica",
                            LastName = "Garcia",
                            NationalCode = "1234567895",
                            PhoneNumber = "09123000006",
                            Role = 0,
                            UserName = "09123000006"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1989, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "Henry",
                            FirstName = "Daniel",
                            LastName = "Miller",
                            NationalCode = "1234567896",
                            PhoneNumber = "09123000007",
                            Role = 0,
                            UserName = "09123000007"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1996, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "Charles",
                            FirstName = "Laura",
                            LastName = "Davis",
                            NationalCode = "1234567897",
                            PhoneNumber = "09123000008",
                            Role = 0,
                            UserName = "09123000008"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1980, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "Root",
                            FirstName = "Admin",
                            LastName = "System",
                            NationalCode = "1234567898",
                            PhoneNumber = "09123000009",
                            Role = 1,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1991, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "Richard",
                            FirstName = "Kevin",
                            LastName = "Wilson",
                            NationalCode = "1234567899",
                            PhoneNumber = "09123000010",
                            Role = 0,
                            UserName = "09123000010"
                        });
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.VehicleEntity.Entity.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ManufacturerCompany")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            Color = "White",
                            FuelType = "Gasoline",
                            IsActive = true,
                            ManufacturerCompany = "Toyota Motor Corporation",
                            Name = "Corolla",
                            Plate = "12A34567",
                            ProductionYear = 2018,
                            UserId = 1,
                            VehicleType = "Ride",
                            Vin = "JTDBR32E530123456"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Honda",
                            Color = "Black",
                            FuelType = "Gasoline",
                            IsActive = true,
                            ManufacturerCompany = "Honda Motor Company",
                            Name = "Civic",
                            Plate = "23B45678",
                            ProductionYear = 2019,
                            UserId = 2,
                            VehicleType = "Ride",
                            Vin = "JHMFA16586S123456"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Tesla",
                            Color = "Blue",
                            FuelType = "Electricity",
                            IsActive = true,
                            ManufacturerCompany = "Tesla Inc",
                            Name = "Model Three",
                            Plate = "34C56789",
                            ProductionYear = 2021,
                            UserId = 3,
                            VehicleType = "Ride",
                            Vin = "5YJ3E1EA7KF123456"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Mercedes",
                            Color = "Silver",
                            FuelType = "CNG",
                            IsActive = true,
                            ManufacturerCompany = "Mercedes Benz Trucks",
                            Name = "Actros",
                            Plate = "45D67890",
                            ProductionYear = 2017,
                            UserId = 4,
                            VehicleType = "Truck",
                            Vin = "WDB9634031L123456"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Ford",
                            Color = "White",
                            FuelType = "Gasoline",
                            IsActive = true,
                            ManufacturerCompany = "Ford Motor Company",
                            Name = "Transit",
                            Plate = "56E78901",
                            ProductionYear = 2016,
                            UserId = 5,
                            VehicleType = "Bus",
                            Vin = "WF0XXXTTGXK123456"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Toyota",
                            Color = "Red",
                            FuelType = "SuperGasoline",
                            IsActive = true,
                            ManufacturerCompany = "Toyota Motor Corporation",
                            Name = "Yaris",
                            Plate = "67F89012",
                            ProductionYear = 2020,
                            UserId = 6,
                            VehicleType = "Taxi",
                            Vin = "JTDKT923975123456"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Honda",
                            Color = "Red",
                            FuelType = "Gasoline",
                            IsActive = true,
                            ManufacturerCompany = "Honda Motor Company",
                            Name = "CBR",
                            Plate = "78G90123",
                            ProductionYear = 2022,
                            UserId = 7,
                            VehicleType = "Motorcycle",
                            Vin = "MLHPC4567M5123456"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Toyota",
                            Color = "Gray",
                            FuelType = "CNG",
                            IsActive = true,
                            ManufacturerCompany = "Toyota Motor Corporation",
                            Name = "Hilux",
                            Plate = "89H01234",
                            ProductionYear = 2015,
                            UserId = 8,
                            VehicleType = "Truck",
                            Vin = "MR0EX3CD901123456"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Toyota",
                            Color = "Black",
                            FuelType = "Gasoline",
                            IsActive = false,
                            ManufacturerCompany = "Toyota Motor Corporation",
                            Name = "Camry",
                            Plate = "90J12345",
                            ProductionYear = 2018,
                            UserId = 10,
                            VehicleType = "Ride",
                            Vin = "4T1BF1FK5HU123456"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Mercedes",
                            Color = "White",
                            FuelType = "CNG",
                            IsActive = true,
                            ManufacturerCompany = "Mercedes Benz Vans",
                            Name = "Sprinter",
                            Plate = "11K23456",
                            ProductionYear = 2014,
                            UserId = 1,
                            VehicleType = "Bus",
                            Vin = "WD3PE8CC6D5123456"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Honda",
                            Color = "Silver",
                            FuelType = "SuperGasoline",
                            IsActive = true,
                            ManufacturerCompany = "Honda Motor Company",
                            Name = "Accord",
                            Plate = "22L34567",
                            ProductionYear = 2019,
                            UserId = 2,
                            VehicleType = "Ride",
                            Vin = "1HGCV1F34JA123456"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Ford",
                            Color = "Green",
                            FuelType = "Gasoline",
                            IsActive = true,
                            ManufacturerCompany = "Ford Motor Company",
                            Name = "Ranger",
                            Plate = "33M45678",
                            ProductionYear = 2020,
                            UserId = 3,
                            VehicleType = "Truck",
                            Vin = "1FTER4FH5KLA12345"
                        });
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.Appointments.Entity.Appointment", b =>
                {
                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.TimeSlotEntity.Entity.TimeSlot", "TimeSlot")
                        .WithOne("Appointment")
                        .HasForeignKey("VehicleInspectionAppointmentSystem.Domain.Models.Appointments.Entity.Appointment", "TimeSlotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.VehicleEntity.Entity.Vehicle", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TimeSlot");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.Centers.Entity.Center", b =>
                {
                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.CityEntity.Entity.City", "City")
                        .WithMany("Centers")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.CityEntity.Entity.City", b =>
                {
                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.ProvinceEntity.Entity.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.TechnicalInspectionEntity.Entity.TechnicalInspection", b =>
                {
                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.Appointments.Entity.Appointment", "Appointment")
                        .WithOne("TechnicalInspection")
                        .HasForeignKey("VehicleInspectionAppointmentSystem.Domain.Models.TechnicalInspectionEntity.Entity.TechnicalInspection", "AppointmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.VehicleEntity.Entity.Vehicle", "Vehicle")
                        .WithMany("TechnicalInspections")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.TimeSlotEntity.Entity.TimeSlot", b =>
                {
                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.Centers.Entity.Center", "Center")
                        .WithMany("TimeSlots")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.VehicleEntity.Entity.Vehicle", b =>
                {
                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.UserEntity.Entity.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.Appointments.Entity.Appointment", b =>
                {
                    b.Navigation("TechnicalInspection")
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.Centers.Entity.Center", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.CityEntity.Entity.City", b =>
                {
                    b.Navigation("Centers");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.ProvinceEntity.Entity.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.TimeSlotEntity.Entity.TimeSlot", b =>
                {
                    b.Navigation("Appointment")
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.UserEntity.Entity.User", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.VehicleEntity.Entity.Vehicle", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("TechnicalInspections");
                });
#pragma warning restore 612, 618
        }
    }
}
