// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleInspectionAppointmentSystem.Infrastructure.Common;

#nullable disable

namespace VehicleInspectionAppointmentSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608112104_AddSeedDataToCenter")]
    partial class AddSeedDataToCenter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.Appointments.Entity.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TimeSlotId")
                        .IsUnique();

                    b.HasIndex("VehicleId", "TimeSlotId")
                        .IsUnique();

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.Centers.Entity.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CenterCode")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DailyMaxCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ManagerName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CenterCode")
                        .IsUnique();

                    b.HasIndex("CityId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Centers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "No. 15, Shariati Street, Tehran",
                            CenterCode = 1001,
                            CityId = 1,
                            DailyMaxCapacity = 20,
                            ManagerName = "Michael Anderson",
                            Name = "North Tehran Technical Inspection Center",
                            PhoneNumber = "09121001001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "No. 42, Azadi Avenue, Tehran",
                            CenterCode = 1002,
                            CityId = 1,
                            DailyMaxCapacity = 18,
                            ManagerName = "Daniel Brown",
                            Name = "West Tehran Vehicle Inspection Center",
                            PhoneNumber = "09121001002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "No. 8, Imam Street, Rey",
                            CenterCode = 1003,
                            CityId = 2,
                            DailyMaxCapacity = 15,
                            ManagerName = "Robert Wilson",
                            Name = "Rey Central Inspection Center",
                            PhoneNumber = "09121001003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "No. 22, Chaharbagh Avenue, Isfahan",
                            CenterCode = 2001,
                            CityId = 3,
                            DailyMaxCapacity = 20,
                            ManagerName = "James Miller",
                            Name = "Isfahan Main Inspection Center",
                            PhoneNumber = "09121002001"
                        },
                        new
                        {
                            Id = 5,
                            Address = "No. 11, Fin Road, Kashan",
                            CenterCode = 2002,
                            CityId = 4,
                            DailyMaxCapacity = 14,
                            ManagerName = "William Davis",
                            Name = "Kashan Vehicle Safety Center",
                            PhoneNumber = "09121002002"
                        },
                        new
                        {
                            Id = 6,
                            Address = "No. 31, Zand Boulevard, Shiraz",
                            CenterCode = 3001,
                            CityId = 5,
                            DailyMaxCapacity = 20,
                            ManagerName = "Thomas Moore",
                            Name = "Shiraz Central Technical Inspection",
                            PhoneNumber = "09121003001"
                        },
                        new
                        {
                            Id = 7,
                            Address = "No. 19, Persepolis Road, Marvdasht",
                            CenterCode = 3002,
                            CityId = 6,
                            DailyMaxCapacity = 12,
                            ManagerName = "Christopher Taylor",
                            Name = "Marvdasht Vehicle Inspection Station",
                            PhoneNumber = "09121003002"
                        },
                        new
                        {
                            Id = 8,
                            Address = "No. 61, Vakilabad Boulevard, Mashhad",
                            CenterCode = 4001,
                            CityId = 7,
                            DailyMaxCapacity = 19,
                            ManagerName = "Matthew Clark",
                            Name = "Mashhad East Inspection Center",
                            PhoneNumber = "09121004001"
                        },
                        new
                        {
                            Id = 9,
                            Address = "No. 5, Attar Street, Neyshabur",
                            CenterCode = 4002,
                            CityId = 8,
                            DailyMaxCapacity = 13,
                            ManagerName = "Anthony Lewis",
                            Name = "Neyshabur Technical Inspection Center",
                            PhoneNumber = "09121004002"
                        },
                        new
                        {
                            Id = 10,
                            Address = "No. 77, Elgoli Road, Tabriz",
                            CenterCode = 5001,
                            CityId = 9,
                            DailyMaxCapacity = 20,
                            ManagerName = "Mark Walker",
                            Name = "Tabriz Main Vehicle Inspection Center",
                            PhoneNumber = "09121005001"
                        },
                        new
                        {
                            Id = 11,
                            Address = "No. 14, Sahand Avenue, Maragheh",
                            CenterCode = 5002,
                            CityId = 10,
                            DailyMaxCapacity = 11,
                            ManagerName = "Steven Hall",
                            Name = "Maragheh Road Safety Inspection Center",
                            PhoneNumber = "09121005002"
                        });
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.CityEntity.Entity.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ProvinceCode")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityCode")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityCode = 101,
                            Name = "Tehran",
                            ProvinceCode = 21,
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            CityCode = 102,
                            Name = "Rey",
                            ProvinceCode = 21,
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 3,
                            CityCode = 201,
                            Name = "Isfahan",
                            ProvinceCode = 31,
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 4,
                            CityCode = 202,
                            Name = "Kashan",
                            ProvinceCode = 31,
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 5,
                            CityCode = 301,
                            Name = "Shiraz",
                            ProvinceCode = 71,
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 6,
                            CityCode = 302,
                            Name = "Marvdasht",
                            ProvinceCode = 71,
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 7,
                            CityCode = 401,
                            Name = "Mashhad",
                            ProvinceCode = 51,
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 8,
                            CityCode = 402,
                            Name = "Neyshabur",
                            ProvinceCode = 51,
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 9,
                            CityCode = 501,
                            Name = "Tabriz",
                            ProvinceCode = 41,
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 10,
                            CityCode = 502,
                            Name = "Maragheh",
                            ProvinceCode = 41,
                            ProvinceId = 5
                        });
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.ProvinceEntity.Entity.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProvinceCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProvinceCode")
                        .IsUnique();

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tehran",
                            ProvinceCode = 101
                        },
                        new
                        {
                            Id = 2,
                            Name = "Isfahan",
                            ProvinceCode = 102
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fars",
                            ProvinceCode = 103
                        },
                        new
                        {
                            Id = 4,
                            Name = "Khorasan Razavi",
                            ProvinceCode = 104
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mazandaran",
                            ProvinceCode = 105
                        });
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.TechnicalInspectionEntity.Entity.TechnicalInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("VehicleVin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("VehicleId");

                    b.ToTable("TechnicalInspections");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.TimeSlotEntity.Entity.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsReserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("TimeSlotDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.UserEntity.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Password")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Password");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.VehicleEntity.Entity.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ManufacturerCompany")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.Appointments.Entity.Appointment", b =>
                {
                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.TimeSlotEntity.Entity.TimeSlot", "TimeSlot")
                        .WithOne("Appointment")
                        .HasForeignKey("VehicleInspectionAppointmentSystem.Domain.Models.Appointments.Entity.Appointment", "TimeSlotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.VehicleEntity.Entity.Vehicle", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TimeSlot");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.Centers.Entity.Center", b =>
                {
                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.CityEntity.Entity.City", "City")
                        .WithMany("Centers")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.CityEntity.Entity.City", b =>
                {
                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.ProvinceEntity.Entity.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.TechnicalInspectionEntity.Entity.TechnicalInspection", b =>
                {
                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.Appointments.Entity.Appointment", "Appointment")
                        .WithOne("TechnicalInspection")
                        .HasForeignKey("VehicleInspectionAppointmentSystem.Domain.Models.TechnicalInspectionEntity.Entity.TechnicalInspection", "AppointmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.VehicleEntity.Entity.Vehicle", "Vehicle")
                        .WithMany("TechnicalInspections")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.TimeSlotEntity.Entity.TimeSlot", b =>
                {
                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.Centers.Entity.Center", "Center")
                        .WithMany("TimeSlots")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.VehicleEntity.Entity.Vehicle", b =>
                {
                    b.HasOne("VehicleInspectionAppointmentSystem.Domain.Models.UserEntity.Entity.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.Appointments.Entity.Appointment", b =>
                {
                    b.Navigation("TechnicalInspection")
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.Centers.Entity.Center", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.CityEntity.Entity.City", b =>
                {
                    b.Navigation("Centers");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.ProvinceEntity.Entity.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.TimeSlotEntity.Entity.TimeSlot", b =>
                {
                    b.Navigation("Appointment")
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.UserEntity.Entity.User", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleInspectionAppointmentSystem.Domain.Models.VehicleEntity.Entity.Vehicle", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("TechnicalInspections");
                });
#pragma warning restore 612, 618
        }
    }
}
